### ISSUE TITLE
Skin according to NEII branding document

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#13]
We want to make it look like neii.gov.au/catalogue with the menu at the top. Andre will provide the branding guidelines (or upload here).

**Comment by ChantelleDoan** [comment]
Steve, after some hunting, we actually do not have a style guide developed for the neii.gov.au website.  Are you able to obtain the style information required by viewing the page source code on neii.gov.au?  If this is not possible we can look at other options to get you the information you require.

**Comment by stevage** [comment]
Yeah, I can do that. 

It would make much more sense for me to wait until we have the new UI ready, otherwise I'll have to repeat a lot of the work. That may be another month or two.

**Comment by ChantelleDoan** [comment]
Great thanks Steve.  We also have a 72dpi fractal image for the background.  Let me know if this will be sufficient.

[cid:image002.jpg@01D18350.F1A41620]

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by stevage** [comment]
Hmm, that didn't attach - try again?

**Comment by ChantelleDoan** [comment]
Hi Steve,

I was unable to successfully include the image previously so am also sending it to your email.

Here it is.

[cid:image002.jpg@01D18350.F1A41620]
Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by stevage** [comment]
![image001 1](https://cloud.githubusercontent.com/assets/678344/14197791/54e5c5de-f81e-11e5-9c63-3132465fc41d.jpg)

**Comment by stevage** [comment]
I talked through a couple of options for skinning with one of our UI designers, and we thought that rather than trying to incorporate the menu etc into the viewer itself, it might be better to have a splash screen within your existing site which gives an overview of what the Viewer does, and then a button to launch it.

That is, when the user clicks "NEII Viewer" on the menu bar, they'd arrive at a page that looks much like http://neii.gov.au/about, that is managed by you within your CMS. It would have text, probably a screenshot, and at the bottom, a prominent button "Launch the viewer". The Viewer itself will still be skinned.

Does that sound like a reasonable approach? (The alternative approach was to try to replicate the whole page layout of your site, which wouldn't work so well with our full screen map...)

**Comment by azzerger** [comment]
Steve, the idea of a more comprehensive Viewer splash page at neii.gov.au does make sense but perhaps not necessarily as a replacement but complement to the re-skinning concept - I think when we mean re-skinning it can be relatively minor - for example even the use of the font we use at neii.gov.au to replace the font for the text that states 'National Environmental Information Infrastructure' and use the grey/green we use as the background would serve the purpose

This could extend to the about pages also - or perhaps we host the about pages on neii.gov.au and you point to those - i suspect a few minor content treatments like that would ensure they look more integrated. 

I even noticed that when a user selects About the Browser tab says 'NICTA National Map: Info" - hence changing this to say NEII Viewer: About would help with the integration challenge (from a content rather than design perspective). 

Happy to hear your thoughts or perhaps we need to discuss beyond GitHub - I think its quite simple and if completed at multiple points its not so much a re-skinning but more a content integration challenge. 

Andre

**Comment by stevage** [comment]
Ok, I've done a basic reskin based on the old UI. I'll have to do it again when we get the new UI, so I don't want to spend too long tweaking details, but happy to fix links etc like you suggest.

Now visible at http://nationalmap.research.nicta.com.au/neii/

<img width="1401" alt="screenshot 2016-04-01 17 36 38" src="https://cloud.githubusercontent.com/assets/678344/14199461/4dc04768-f830-11e5-8e44-bd0b0f1882ed.png">

**Comment by azzerger** [comment]
Steve, that's a great forward step - I agree that its best to wait given related UI enhancements - Chantelle and I will have a chat next week and update the github re other minor changes. On reflection I think we should host the about pages on neii.gov.au - its a very easy migration exercise and it provides us content control over those pages which is helpful. Andre

**Comment by stevage** [comment]
Great, I was hoping you'd say that. :)

**Comment by stevage** [comment]
I'll call this done for now, and we can make a new issue to reskin the new UI later when it's ready.
