### ISSUE TITLE
Useage statistics on Viewer

### ISSUE THREAD

**Issue by azzerger** [TerriaJS/neii-viewer#17]
Steve

We never included this in the initial statement of work (major oversight) but does your TerriaJS work provide an ability to generate access/user statistics from our Viewer - even basic statistics on number of page/layer views etc. I am not suggesting a body of work to achieve this from first principles but just asking whether you have this capability in place?

Andre

**Comment by stevage** [comment]
Please send us your Google Analytics key and we'll add it in.

**Comment by ChantelleDoan** [comment]
Chantelle to follow up with Digital Data (Adam Hough) and Viv on obtaining a key.

**Comment by ChantelleDoan** [comment]
Hi Steve,

Please refer to below comment from Stefan Willoughby from the Digital Data Delivery team:


​Would it be possible to update the viewer to use its internal analytics function after we add the GA code?



I'm not sure what data this will send but any interaction data is more valuable than pageview data.



http://nationalmap.gov.au/build/TerriaJS/doc/Terria.html​



analytics :ConsoleAnalytics|GoogleAnalytics

Gets or sets the instance to which to report Google Analytics-style log events. If a global ga function is defined, this defaults to GoogleAnalytics. Otherwise, it defaults toConsoleAnalytics.

Type:
·         ConsoleAnalytics | GoogleAnalytics
Source:
·         Models/Terria.js<http://nationalmap.gov.au/build/TerriaJS/doc/Models_Terria.js.html>, line 86<http://nationalmap.gov.au/build/TerriaJS/doc/Models_Terria.js.html#line86>




Please note: I work part time and am not in the office alternate Fridays.

Stefan Willoughby | Digital analyst and Solutions architect

Digital Data Delivery | Information Systems & Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 8, 700 Collins Street, Docklands VIC 3008
+61 3 8638 8262 | 0417 109 145
S.Willoughby@bom.gov.au<mailto:S.Willoughby@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au>


Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by ChantelleDoan** [comment]
Hi Steve,

Here is the new GA Code for NEII Viewer from Stefan.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62048953-2', 'auto');
  ga('send', 'pageview');

</script>


Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

From: Chantelle Doan
Sent: Wednesday, 29 June 2016 11:02 AM
To: 'TerriaJS/neii-viewer'; TerriaJS/neii-viewer
Cc: Steve Bennett; Adam Hough
Subject: RE: [TerriaJS/neii-viewer] Useage statistics on Viewer (#17) [SEC=UNCLASSIFIED]

Hi Steve,

Please refer to below comment from Stefan Willoughby from the Digital Data Delivery team:


​Would it be possible to update the viewer to use its internal analytics function after we add the GA code?



I'm not sure what data this will send but any interaction data is more valuable than pageview data.



http://nationalmap.gov.au/build/TerriaJS/doc/Terria.html​



analytics :ConsoleAnalytics|GoogleAnalytics

Gets or sets the instance to which to report Google Analytics-style log events. If a global ga function is defined, this defaults to GoogleAnalytics. Otherwise, it defaults toConsoleAnalytics.

Type:
·         ConsoleAnalytics | GoogleAnalytics
Source:
·         Models/Terria.js<http://nationalmap.gov.au/build/TerriaJS/doc/Models_Terria.js.html>, line 86<http://nationalmap.gov.au/build/TerriaJS/doc/Models_Terria.js.html#line86>




Please note: I work part time and am not in the office alternate Fridays.

Stefan Willoughby | Digital analyst and Solutions architect

Digital Data Delivery | Information Systems & Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 8, 700 Collins Street, Docklands VIC 3008
+61 3 8638 8262 | 0417 109 145
S.Willoughby@bom.gov.au<mailto:S.Willoughby@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au>


Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by AnaBelgun** [comment]
hi @martin-bom it seems that we have implemented the NEII Google Analytics key but we were never given access to the stats. Is it possible to find out the stats from whom has access now in the Bureau or give us access?

**Comment by martin-bom** [comment]
Hi @AnaBelgun the GA key and access are managed by our Web Analytics Team. I can access the statistics if you are using the same key. Thank you.

**Comment by AnaBelgun** [comment]
[User data for 2020 ](https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NEII%20Viewer/NEII%20Usage%20statistics%20and%20feedback/[DataViewer_Users_2020_Stats.xlsx](https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NEII%20Viewer/NEII%20Usage%20statistics%20and%20feedback/DataViewer_Users_2020_Stats.xlsx?d=w5e6aa1cafb0a4900aa223dacac2629a3&csf=1&web=1&e=yxEMog)?d=w5e6aa1cafb0a4900aa223dacac2629a3&csf=1&web=1&e=yxEMog)
