### ISSUE TITLE
Remote catalog file

### ISSUE THREAD

**Issue by marissabyrnes** [TerriaJS/neii-viewer#33]
Hi,

If we use a remote catalog file (option 3 from http://terria.io/Documentation/CatalogManagement/Initialization-File/), does the file extension have to be .json?  Or can it be a script that returns json?

> `3`.  Store it anywhere on the web (on a CORS-enabled server). Add the complete URL (including .json) to the URL, after #. For instance, nationalmap.gov.au/#http://example.com/mycatalog.json. This method is useful when developing services for a Terria instance which you don't directly control, and for rapidly previewing changes which you can also share with people.

Thanks,
Marissa

**Comment by kring** [comment]
> Or can it be a script that returns json?

It can be a script that returns JSON, but the URL does need to end with `.json` at the moment.  You may be able to "fake it" with a URL like `my/service/url/whatever?f=.json` where your service simply ignores the `f=.json` part of the URL.

**Comment by marissabyrnes** [comment]
Thanks

**Comment by marissabyrnes** [comment]
Hi,
I have tried to "fake it"...but with no luck...

This works:
http://viewer.neii.gov.au/#https://raw.githubusercontent.com/TerriaJS/neii-viewer/master/wwwroot/init/neii-nemsr.json

But this doesn't:
http://viewer.neii.gov.au/#https://raw.githubusercontent.com/TerriaJS/neii-viewer/master/wwwroot/init/neii-nemsr.json?test=test.json

(the URL that I am using isn't accessible outside our network)

Any other ideas?  Apart from rewrite?

Thanks

**Comment by marissabyrnes** [comment]
I have added some redirects and it works as expected on staging.  But I get a proxy error on the production viewer.  Will this error still exist when we load an external config via the intitialisation file instead of the querystring?

The URLs I am using to test are (which only available internally as they are internal dev servers): 
- http://viewer.neii.gov.au/#http://[DEV_SERVER_URL]/cgi-bin/nemsr/get_viewer_config.json
- http://nationalmap.research.nicta.com.au/neii/#http://[DEV_SERVER_URL]/cgi-bin/nemsr/get_viewer_config.json

I have put in a change to the intialisation config for the master branch to be able to test this (the URL I used should become available in the next 24 hours) 
https://github.com/TerriaJS/neii-viewer/compare/master...marissabyrnes:patch-1

**Comment by marissabyrnes** [comment]
Update:

I am not getting the proxy error with:  http://nationalmap.research.nicta.com.au/neii/#http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json

As above, I made a patch in the master branch of the neii viewer - is this the right process to get it to staging?

**Comment by marissabyrnes** [comment]
Update

- Chrome isn't getting the proxy error
- Firefox is getting the proxy error:
An error occurred while loading initialization information from proxy/http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json. This may indicate that you followed an invalid link or that there is a problem with your Internet connection.

- http://viewer.neii.gov.au/#http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json (this should now be accessible)

Also, chrome displays the same proxy error if I try and load the config file from our DEV URL (http://viewer.neii.gov.au/#http://[DEV_SERVER_URL]/cgi-bin/nemsr/get_viewer_config.json)

**Comment by stevage** [comment]
Hi Marissa,
  Sorry I've been on leave for three weeks, so just catching up now.

Re: the technique of adding `?f=.json` not working, I'm not sure exactly, but I think it will work when we update NEII Viewer to the new UI.

>Firefox is getting the proxy error: An error occurred while loading initialization information from proxy/http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json. This may indicate that you followed an invalid link or that there is a problem with your Internet connection.

I don't know why Firefox is displaying an error for you when loading http://viewer.neii.gov.au/#http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json . It works ok for me. Perhaps you have an old version of Firefox?

>Also, chrome displays the same proxy error if I try and load the config file from our DEV URL 

I can guess what's going on here. It will probably help if you realise the way Terria decides whether to use a proxy or access the data directly from the browser:
- if the server is listed as supporting CORS in the [browser config](https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/config.json) (which your dev server isn't), it's accessed directly
- otherwise, if it's in the `allowProxyFor` list in the [server config](https://github.com/TerriaJS/neii-viewer/blob/master/devserverconfig.json) (which your dev server isn't) then it's accessed via proxy
- otherwise, we attempt to connect directly and hope that the server supports CORS. If you're getting an error message, probably your server doesn't support CORS, or perhaps it's returning something broken - Terria can't necessarily distinguish.

**Comment by marissabyrnes** [comment]
Thanks Steve.

So maybe the best way is to:
- add neii.bom.gov.au to the server config
- add the config url to the browser config (I did a patch for this, but not sure if that was the process i was meant to follow?)

We would like to do this on the staging viewer, and then have a chat tomorrow about when/how we move it to the production viewer.

**Comment by stevage** [comment]
Hmm. I was wrong about one thing: the config setting that tells Terria that a server supports CORS isn't in `config.json`, it's actually in an init file. Which means probably it won't work for loading another init file - because they all get fetched simultaneously.

I'm not sure how to proceed from here, but I have my thinking cap on.

**Comment by stevage** [comment]
Hmm, putting it in the first init file seems to work (see [staging](http://nationalmap.research.nicta.com.au/neii/)) but that doesn't seem like a reliable solution. I've raised issue TerriaJS/TerriaJS#1959

**Comment by ChantelleDoan** [comment]
Hi Steve,
We are ready to go live with NEMSR.  Anytime you have a chance today or tomorrow, could you help me roll this out to production so the production NEII Viewer this using the nemr config file on the BOM server.  Thanks.
https://github.com/TerriaJS/neii-viewer/compare/master...marissabyrnes:patch-1

Regards,
Chantelle

**Comment by stevage** [comment]
Can you confirm that you have checked the new UI version (http://nationalmap.research.nicta.com.au/neii-newui/) and are happy for it to go into prod?

**Comment by ChantelleDoan** [comment]
Hi Steve,
Sorry for the misunderstanding.  I only mean to point the current NEII Viewer production to use the nemsr config file residing on our server for now, not the complete new UI version.  Once we have NEMSR in production we can continue to test the new UI further.

To copy the https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/config.json
from the master branch to the production branch.

**Comment by ChantelleDoan** [comment]
I managed to action this change to config.json in the production branch.  Waiting to be able to see this stage on the Viewer now.

**Comment by ChantelleDoan** [comment]
Hi Steve,
I still don't see the NEMSR records on the Viewer yet.  Could you look into this for me?  Thanks.

**Comment by stevage** [comment]
You're not seeing it here? http://nationalmap.research.nicta.com.au/neii/ What should be displaying differently from what you're seeing?

**Comment by ChantelleDoan** [comment]
Hi Steve,


I am expecting to see the "Environment Monitoring Sites Register" layers.  I do see it at http://nationalmap.research.nicta.com.au/neii/

And also expecting to see it at http://neii.gov.au/viewer/ but currently it is not showing even after I made the changes to the config.json<https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/config.json> file to use the nemsr config file residing on the BOM server.


http://nationalmap.research.nicta.com.au/neii/
[cid:image001.png@01D208FA.24E0E390]


http://neii.gov.au/viewer/

[cid:image002.png@01D208FA.24E0E390]

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | chantelle.doan@bom.gov.au<mailto:chantelle.doan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by stevage** [comment]
Just to make sure we're on the same page about how this stuff works:

- nationalmap.research.nicta.com.au/neii-viewer automatically updates from the `master` branch every hour, but due to a caching proxy on that server, some changes aren't visible to everyone.
- neii.gov.au/viewer is built from the `production` branch, but only when we manually redeploy it. There's no automatic process for that. Let us manage the production branch - please don't make any changes directly to it.

I've updated `production` now and requested a redeployment.

It would be really good if you could give us approval of the new ui version as soon as possible. Until that happens we're stuck maintaining both old and new ui versions, which is a bit of a pain.
