### ISSUE TITLE
Update NEMSR catalog item

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#45]
In the current production viewer at http://viewer.neii.gov.au/, on loading or refreshing this page, the Viewer is currently calling the NEMSR config file located on the BOM server located at http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json.  This loads the Environmental Monitoring Sites Register dropdown menu that has been automatically generated on the BOM server everytime a new data layer is loaded to the NEII system.  

- [x] http://neii-viewer-2016-10-06.neiiviewer.nicta.com.au/ should be calling the `get_viewer_config.json` file on load and refresh.  Could you check that it is currently performing this function? 

- [x] BOM to action:  to insert space after the group name eg. Air (3) (@ChantelleDoan)

![image](https://cloud.githubusercontent.com/assets/18452161/20126015/daa96ff2-a685-11e6-83e3-29ea442fc15c.png)

- [x] check the use of eJSON

**Comment by RacingTadpole** [comment]
Yes, `get_viewer_config.json` is being accessed by the new version, and it is cached for 60 seconds.

Re the third checkbox about `eJSON`, to change the catalog, you need to make your changes to the [datasources directory](https://github.com/TerriaJS/neii-viewer/tree/neii-newui/datasources) now, instead of the `wwwroot/init` directory.

(This points to the `neii-newui` branch for now - once we merge these changes into master, the link will be more straightforward.)
