### ISSUE TITLE
SOS2: User feedback #16: Limit of 250 timeseries returned per GetObservation request

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#97]
Hi Arthur,

Jo followed up with Kisters (supplier and developer of the WDO/WISKI products)  - Chis Michl regarding the SOS2 limitation on rows returned.  He advised the limit has been turned off and there may be issues with the GetObservation request.

For Kisters to investigate this issue further, could you send the GetObservation script to waterdatasupport@bom.gov.au.  Thanks Arthur.

**Comment by RacingTadpole** [comment]
Thanks Chantelle. For the record, here's the main part of the email I've sent:

The script I’m using to call the SOS API is in javascript, at https://github.com/TerriaJS/terriajs/blob/master/lib/Models/SensorObservationServiceCatalogItem.js#L482-L501 . The SOAP template it uses is [here](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/SensorObservationServiceRequestTemplate.xml) (this uses [Mustache](https://github.com/janl/mustache.js/) formatting).

You can see it in action via the NEII viewer with "#build/TerriaJS/test/init/bom.json" appended to the URL. Then if you look in the Network tab on the developer tools when you click on “Storage Levels”, you’ll see it fires off three calls to http://www.bom.gov.au/waterdata/services, because there are ~600 features, and so it slices them into three groups of ~200 to get around the size limit.

I just tried changing the limit to 450 in my local version of the viewer, to see if the limit had been lifted, but I get the error response: “ResponseExceedsSizeLimit - The search terms matched more than 250 timeseries in the datasource. Please limit your request further.”

When I change the limit to 700, I get a different error: "ResponseExceedsSizeLimit - You cannot request more than 500 features at once."

**Comment by ChantelleDoan** [comment]
Thanks Arthur.  The WDO team is following up with Kisters and hopefully we can come to a resolution shortly.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | chantelle.doan@bom.gov.au<mailto:chantelle.doan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>
[app email badge.jpg]<http://www.bom.gov.au/app>

**Comment by ChantelleDoan** [comment]
Hi Arthur,
Good news, the WDO team advised the SOS limitation set on the number of data values returned has now been removed to enable more data to be pulled.  Let us know how the testing goes.  Thanks Arthur.

**Comment by ChantelleDoan** [comment]
Hi Arthur,
Further clarification from WDO:
The SOS2 limitations were not actually removed, they were increased – hopefully this will mean the same thing to Data61 and others – they won't encounter limits. The changes to the limitations are:
Max Timeseries : from 250 to 10000
Max Values: from 250000 to 2000000

**Comment by RacingTadpole** [comment]
Unfortunately I am still getting the error:

> You cannot request more than 500 features at once.

when I ask for 1000 features from http://www.bom.gov.au/waterdata/services, using http://bom.gov.au/waterdata/services/tstypes/Pat3_C_B_1_YearlyMean and http://bom.gov.au/waterdata/services/parameters/Water Course Level.

I can ask for 450 features/request over 10 separate requests, and that works, but it takes between 30 and 80 seconds per request (and only 6 can occur simultaneously), which means the user clicks on the item and has to wait a few minutes to see anything load. (I’m asking for 40 observations per feature.)

I’m guessing that without limits on the number of features per request, the server would still take at least a minute to respond.  Is there any way to make this faster?  Otherwise, Chantelle, do you think NEII-viewer users would be prepared to wait that long?  If not, we may need to stick with the current approach after all, where the features are loaded without their observation data (which takes the server 3 seconds or so).
